services:
  db:
    image: postgres:15
    container_name: lyceum_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: lyceum_auth
    ports:
      - "5434:5432"